"""Centralized deterministic localization utilities."""

from __future__ import annotations


SUPPORTED_LANGUAGES = {"en", "zh-CN", "zh-TW"}


TEXT = {
    "en": {
        "medium": "Medium",
        "high": "High",
        "low": "Low",
        "source_document": "Source Document",
        "not_available": "Not available",
    },
    "zh-CN": {
        "medium": "中等",
        "high": "高",
        "low": "低",
        "source_document": "输入文档",
        "not_available": "不可用",
    },
    "zh-TW": {
        "medium": "中等（繁體）",
        "high": "高（繁體）",
        "low": "低（繁體）",
        "source_document": "輸入文件",
        "not_available": "不可用",
    },
}


BRIEF_REPLACEMENTS = {
    "zh-CN": {
        "# Executive Intelligence Brief": "# 高管情报简报",
        "# Analyst Reasoning Brief": "# 分析师推理简报",
        "# Executive Summary": "# 高管摘要",
        "## Executive Summary": "## 高管摘要",
        "## Agent Execution Trace": "## 代理执行轨迹",
        "## Tool Decisions": "## 工具决策",
        "## Analysis Path": "## 分析路径",
        "## Key Issue": "## 核心议题",
        "## Current Event Context": "## 当前事件背景",
        "## Scenario Classification": "## 情境分类",
        "## Extracted Entities": "## 抽取实体",
        "## Historical Analogues": "## 历史相似案例",
        "## Historical Outcomes": "## 历史结果",
        "## Strategic Lessons": "## 战略经验",
        "## Evidence Credibility Note": "## 证据可信度说明",
        "## Decision Considerations": "## 决策考虑事项",
        "## Current Context": "## 当前背景",
        "## Similarities and Differences": "## 相似点与差异",
        "## Business Considerations": "## 商业考虑事项",
        "## Operational Considerations": "## 运营考虑事项",
        "## Geopolitical Considerations": "## 地缘政治考虑事项",
        "## Mechanisms Detected": "## 检测到的机制",
        "## Competing Interpretations": "## 竞争性解释",
        "## Multi-Lens Analysis": "## 多视角分析",
        "## Supporting Evidence": "## 支持性证据",
        "## Weakening Evidence": "## 削弱性证据",
        "## Missing Evidence": "## 缺失证据",
        "## Historical Response Patterns": "## 历史应对模式",
        "## Cross-Domain Lessons": "## 跨领域经验",
        "## Monitoring Considerations": "## 监测考虑事项",
        "## Strategic Questions": "## 战略问题",
        "## Analyst Notes": "## 分析师注释",
        "## Limitations": "## 局限性",
        "## Evidence Sources": "## 证据来源",
        "### Evidence Trace": "### 证据追踪",
        "**Event type:**": "**事件类型：**",
        "**Primary actor:**": "**主要参与者：**",
        "**Secondary actor:**": "**次要参与者：**",
        "**Affected sectors:**": "**受影响行业：**",
        "**Affected regions:**": "**受影响地区：**",
        "**Policy domain:**": "**政策领域：**",
        "**Strategic significance:**": "**战略意义：**",
        "**Event summary:**": "**事件摘要：**",
        "**Confidence:**": "**置信标签：**",
        "**Limitations:**": "**局限性：**",
        "**Primary scenario:**": "**主要情境：**",
        "**Matched keywords:**": "**匹配关键词：**",
        "**Classification confidence:**": "**分类置信标签：**",
        "**Evidence trace:**": "**证据追踪：**",
        "**Title:**": "**标题：**",
        "**Core issue:**": "**核心问题：**",
        "**Summary:**": "**摘要：**",
        "**Actors:**": "**参与者：**",
        "**Countries / regions:**": "**国家 / 地区：**",
        "**Industries:**": "**行业：**",
        "**Policy terms:**": "**政策术语：**",
        "**Companies:**": "**公司：**",
        "**Evidence summary:**": "**证据摘要：**",
        "**Confidence distribution:**": "**置信分布：**",
        "**Source status distribution:**": "**来源状态分布：**",
        "**Reviewer note:**": "**审阅说明：**",
        "**Key limitations:**": "**主要局限性：**",
        "High": "高",
        "Medium": "中等",
        "Low": "低",
        "Source Document": "输入文档",
        "Historical Database": "历史数据库",
        "Current Context KB": "当前背景知识库",
        "Evidence Credibility Layer": "证据可信度层",
        "Decision-support only. No forecasts, probabilities, trading advice, or investment recommendations.": "仅用于决策支持；不提供预测、概率、交易建议或投资建议。",
    },
    "zh-TW": {
        "# Executive Intelligence Brief": "# 高階主管情報簡報",
        "# Analyst Reasoning Brief": "# 分析師推理簡報",
        "# Executive Summary": "# 高階主管摘要",
        "## Executive Summary": "## 高階主管摘要",
        "## Agent Execution Trace": "## 代理執行軌跡",
        "## Tool Decisions": "## 工具決策",
        "## Analysis Path": "## 分析路徑",
        "## Key Issue": "## 核心議題",
        "## Current Event Context": "## 當前事件背景",
        "## Scenario Classification": "## 情境分類",
        "## Extracted Entities": "## 擷取實體",
        "## Historical Analogues": "## 歷史相似案例",
        "## Historical Outcomes": "## 歷史結果",
        "## Strategic Lessons": "## 策略經驗",
        "## Evidence Credibility Note": "## 證據可信度說明",
        "## Decision Considerations": "## 決策考量",
        "## Current Context": "## 當前背景",
        "## Similarities and Differences": "## 相似點與差異",
        "## Business Considerations": "## 商業考量",
        "## Operational Considerations": "## 營運考量",
        "## Geopolitical Considerations": "## 地緣政治考量",
        "## Mechanisms Detected": "## 偵測到的機制",
        "## Competing Interpretations": "## 競爭性解釋",
        "## Multi-Lens Analysis": "## 多視角分析",
        "## Supporting Evidence": "## 支持性證據",
        "## Weakening Evidence": "## 削弱性證據",
        "## Missing Evidence": "## 缺失證據",
        "## Historical Response Patterns": "## 歷史應對模式",
        "## Cross-Domain Lessons": "## 跨領域經驗",
        "## Monitoring Considerations": "## 監測考量",
        "## Strategic Questions": "## 策略問題",
        "## Analyst Notes": "## 分析師註記",
        "## Limitations": "## 限制",
        "## Evidence Sources": "## 證據來源",
        "### Evidence Trace": "### 證據追蹤",
        "**Event type:**": "**事件類型：**",
        "**Primary actor:**": "**主要參與者：**",
        "**Secondary actor:**": "**次要參與者：**",
        "**Affected sectors:**": "**受影響產業：**",
        "**Affected regions:**": "**受影響地區：**",
        "**Policy domain:**": "**政策領域：**",
        "**Strategic significance:**": "**策略意義：**",
        "**Event summary:**": "**事件摘要：**",
        "**Confidence:**": "**信心標籤：**",
        "**Limitations:**": "**限制：**",
        "**Primary scenario:**": "**主要情境：**",
        "**Matched keywords:**": "**匹配關鍵字：**",
        "**Classification confidence:**": "**分類信心標籤：**",
        "**Evidence trace:**": "**證據追蹤：**",
        "**Title:**": "**標題：**",
        "**Core issue:**": "**核心問題：**",
        "**Summary:**": "**摘要：**",
        "**Actors:**": "**參與者：**",
        "**Countries / regions:**": "**國家 / 地區：**",
        "**Industries:**": "**產業：**",
        "**Policy terms:**": "**政策術語：**",
        "**Companies:**": "**公司：**",
        "**Evidence summary:**": "**證據摘要：**",
        "**Confidence distribution:**": "**信心分布：**",
        "**Source status distribution:**": "**來源狀態分布：**",
        "**Reviewer note:**": "**審閱說明：**",
        "**Key limitations:**": "**主要限制：**",
        "High": "高（繁體）",
        "Medium": "中等（繁體）",
        "Low": "低（繁體）",
        "Source Document": "輸入文件",
        "Historical Database": "歷史資料庫",
        "Current Context KB": "當前背景知識庫",
        "Evidence Credibility Layer": "證據可信度層",
        "Decision-support only. No forecasts, probabilities, trading advice, or investment recommendations.": "僅用於決策支持；不提供預測、機率、交易建議或投資建議。",
    },
}


def translate_text(text: str, language: str) -> str:
    """Translate deterministic labels, headings, and confidence terms."""
    if language == "en":
        return text
    replacements = BRIEF_REPLACEMENTS.get(language, {})
    translated = text
    for source, target in replacements.items():
        translated = translated.replace(source, target)
    return translated


def label(key: str, language: str) -> str:
    """Return a localized short label."""
    return TEXT.get(language, TEXT["en"]).get(key, TEXT["en"].get(key, key))
